#!/bin/bash

# loading config.ini
eval $(
  sed -En '
    /^\['filepath']/,/^$/{
      s/^[ \t]*([^:]+)[ \t]*:[ \t]*(.+)[ \t]*$/\1="\2"/p
    }
  ' < config.ini
)

# Direcroty creation
find $TARGETDIR -maxdepth 1 -type f | gawk -F/ '{print $NF}' | ./get_title | sort -u | xargs --no-run-if-empty -I{} mkdir $TARGETDIR/{} 2> /dev/null

# move *.ts into Directory
FOLDER_NAMES=`find $TARGETDIR -type d | gawk -F/ '{print $NF}'`
for folder in $FOLDER_NAMES
do
    find $TARGETDIR -maxdepth 1 -type f -name "*$folder*.ts" | xargs --no-run-if-empty -I{} mv {} $TARGETDIR/$folder/
done
